# Generated by Django 4.2 on 2023-04-18 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Например:20', null=True, verbose_name='Возраст'),
        ),
    ]
